# Generated by Django 6.0.4 on 2026-04-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypark', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha', 'hora_inicio', 'hora_fin', 'plaza'], name='mypark_rese_fecha_e201f4_idx'),
        ),
    ]
