# Generated by Django 6.0.4 on 2026-04-22 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypark', '0002_reserva_mypark_rese_fecha_e201f4_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='matricula',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='La matrícula solo puede contener letras, números, guiones y espacios', regex='^[A-Z0-9\\-\\s]{2,15}$')]),
        ),
    ]
