# Generated by Django 6.0.4 on 2026-04-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypark', '0003_alter_reserva_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoplaza',
            name='color_mapa',
        ),
        migrations.AddField(
            model_name='tipoplaza',
            name='icono',
            field=models.CharField(default='bi-car-front', max_length=50),
        ),
    ]
